### PR TITLE
Initial Mail Configuration

### PR DESCRIPTION
**Pull request by tanneberger**

### CODE REVIEW

**Comment by astro** [comment]
What are the arguments against https://github.com/GoldsteinE/simple-nixos-mailserver?

**Comment by tanneberger** [comment]
I dont know if simple-nixos-mailserver has all the features that we need. But this is a cropped version of the config that runs in prod at @fsr

**Comment by liske** [comment]
> What are the arguments against https://github.com/GoldsteinE/simple-nixos-mailserver?

We just need a smarthost for a outbound mail setup - *simple-nixos-mailserver* looks a little bit oversized.

**Comment by liske** [comment]
superseded by #58

**Pull request closed without merging**
