### PR TITLE
bind9: add new service

### PR DESCRIPTION
**Pull request by liske**
Add bind9 for hidden primary dns setups to provide at least reverse zones for our IX prefix.

The bind9 configuration does **not** allow recursive lookups intentionally. It should be only used as hidden primary to provide zone transfers to known slaves.

I'm unsure about the `networking.resolvconf.useLocalResolver` setting. I explicitly set it to `false` because of the [line 250 in `bind.nix`](https://github.com/NixOS/nixpkgs/blob/a9148e8e8d57820d25ad0abfefb8d8440ff18096/nixos/modules/services/networking/bind.nix#L250C5-L250C5). The local name server should never be used for resolving arbitrary names.

### CODE REVIEW

**Comment by revol-xut** [comment]
Currently, we still use resolvconf when #2 is merged we most probably switch over to systemd.resolvd

**Comment by astro** [comment]
@liske Welcome to Nix! :-)

**Comment by liske** [comment]
> @liske Welcome to Nix! :-)

nix has happened yet :eyes:

**Review by revol-xut — APPROVED** [review]
Looks Good

**Pull request merged**
